[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.6.0"
serde = { version = "1.0.210", features = ["derive"] }